# Setup
title:        Workjoy
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fountainhead
  url:        https://join.Workjoy.online

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown