# Setup
title:        Workjoy
tagline:      Your team communication in one place. Less email, less overload and more productivity. 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Fountainhead
  url:        https://join.Workjoy.online

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown